### YamlMime:ManagedReference
items:
- uid: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator
  commentId: T:Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator
  id: LegacyDynamoDBGatewayListProviderConfigurator
  parent: Orleans.Clustering.DynamoDB
  children:
  - Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  langs:
  - csharp
  - vb
  name: LegacyDynamoDBGatewayListProviderConfigurator
  nameWithType: LegacyDynamoDBGatewayListProviderConfigurator
  fullName: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator
  type: Class
  source:
    remote:
      path: src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: LegacyDynamoDBGatewayListProviderConfigurator
    path: src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
    startLine: 11
  assemblies:
  - Orleans.Clustering.DynamoDB
  namespace: Orleans.Clustering.DynamoDB
  example: []
  syntax:
    content: 'public class LegacyDynamoDBGatewayListProviderConfigurator : ILegacyGatewayListProviderConfigurator'
    content.vb: >-
      Public Class LegacyDynamoDBGatewayListProviderConfigurator

          Inherits ILegacyGatewayListProviderConfigurator
  inheritance:
  - System.Object
  extensionMethods:
  - Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  commentId: M:Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  id: ConfigureServices(System.Object,IServiceCollection)
  parent: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureServices(Object, IServiceCollection)
  nameWithType: LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices(Object, IServiceCollection)
  fullName: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices(System.Object, IServiceCollection)
  type: Method
  source:
    remote:
      path: src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: ConfigureServices
    path: src/AWS/Orleans.Clustering.DynamoDB/Membership/LegacyDynamoDBGatewayListProviderConfigurator.cs
    startLine: 20
  assemblies:
  - Orleans.Clustering.DynamoDB
  namespace: Orleans.Clustering.DynamoDB
  example: []
  syntax:
    content: public void ConfigureServices(object configuration, IServiceCollection services)
    parameters:
    - id: configuration
      type: System.Object
    - id: services
      type: IServiceCollection
    content.vb: Public Sub ConfigureServices(configuration As Object, services As IServiceCollection)
  overload: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Orleans.Clustering.DynamoDB
  commentId: N:Orleans.Clustering.DynamoDB
  isExternal: false
  name: Orleans.Clustering.DynamoDB
  nameWithType: Orleans.Clustering.DynamoDB
  fullName: Orleans.Clustering.DynamoDB
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<LegacyDynamoDBGatewayListProviderConfigurator>()
  nameWithType: ImmutableExt.AsImmutable<LegacyDynamoDBGatewayListProviderConfigurator>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of LegacyDynamoDBGatewayListProviderConfigurator)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator)()
  name.vb: AsImmutable(Of LegacyDynamoDBGatewayListProviderConfigurator)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<LegacyDynamoDBGatewayListProviderConfigurator>
    nameWithType: ImmutableExt.AsImmutable<LegacyDynamoDBGatewayListProviderConfigurator>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of LegacyDynamoDBGatewayListProviderConfigurator)
    nameWithType: ImmutableExt.AsImmutable(Of LegacyDynamoDBGatewayListProviderConfigurator)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices*
  commentId: Overload:Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices
  isExternal: false
  name: ConfigureServices
  nameWithType: LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices
  fullName: Orleans.Clustering.DynamoDB.LegacyDynamoDBGatewayListProviderConfigurator.ConfigureServices
- uid: IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: IServiceCollection
