### YamlMime:ManagedReference
items:
- uid: Orleans.Runtime.OrleansConfigurationException
  commentId: T:Orleans.Runtime.OrleansConfigurationException
  id: OrleansConfigurationException
  parent: Orleans.Runtime
  children:
  - Orleans.Runtime.OrleansConfigurationException.#ctor(SerializationInfo,StreamingContext)
  - Orleans.Runtime.OrleansConfigurationException.#ctor(System.String)
  - Orleans.Runtime.OrleansConfigurationException.#ctor(System.String,Exception)
  langs:
  - csharp
  - vb
  name: OrleansConfigurationException
  nameWithType: OrleansConfigurationException
  fullName: Orleans.Runtime.OrleansConfigurationException
  type: Class
  source:
    remote:
      path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: OrleansConfigurationException
    path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
    startLine: 8
  assemblies:
  - Orleans.Core.Abstractions
  namespace: Orleans.Runtime
  summary: "\nRepresents a configuration exception.\n"
  example: []
  syntax:
    content: 'public class OrleansConfigurationException : Exception'
    content.vb: >-
      Public Class OrleansConfigurationException

          Inherits Exception
  inheritance:
  - System.Object
  extensionMethods:
  - Orleans.Runtime.OrleansConfigurationException.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Orleans.Runtime.OrleansConfigurationException.#ctor(System.String)
  commentId: M:Orleans.Runtime.OrleansConfigurationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Orleans.Runtime.OrleansConfigurationException
  langs:
  - csharp
  - vb
  name: OrleansConfigurationException(String)
  nameWithType: OrleansConfigurationException.OrleansConfigurationException(String)
  fullName: Orleans.Runtime.OrleansConfigurationException.OrleansConfigurationException(System.String)
  type: Constructor
  source:
    remote:
      path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: .ctor
    path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
    startLine: 12
  assemblies:
  - Orleans.Core.Abstractions
  namespace: Orleans.Runtime
  example: []
  syntax:
    content: public OrleansConfigurationException(string message)
    parameters:
    - id: message
      type: System.String
    content.vb: Public Sub New(message As String)
  overload: Orleans.Runtime.OrleansConfigurationException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Orleans.Runtime.OrleansConfigurationException.#ctor(System.String,Exception)
  commentId: M:Orleans.Runtime.OrleansConfigurationException.#ctor(System.String,Exception)
  id: '#ctor(System.String,Exception)'
  parent: Orleans.Runtime.OrleansConfigurationException
  langs:
  - csharp
  - vb
  name: OrleansConfigurationException(String, Exception)
  nameWithType: OrleansConfigurationException.OrleansConfigurationException(String, Exception)
  fullName: Orleans.Runtime.OrleansConfigurationException.OrleansConfigurationException(System.String, Exception)
  type: Constructor
  source:
    remote:
      path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: .ctor
    path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
    startLine: 15
  assemblies:
  - Orleans.Core.Abstractions
  namespace: Orleans.Runtime
  example: []
  syntax:
    content: public OrleansConfigurationException(string message, Exception innerException)
    parameters:
    - id: message
      type: System.String
    - id: innerException
      type: Exception
    content.vb: Public Sub New(message As String, innerException As Exception)
  overload: Orleans.Runtime.OrleansConfigurationException.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Orleans.Runtime.OrleansConfigurationException.#ctor(SerializationInfo,StreamingContext)
  commentId: M:Orleans.Runtime.OrleansConfigurationException.#ctor(SerializationInfo,StreamingContext)
  id: '#ctor(SerializationInfo,StreamingContext)'
  parent: Orleans.Runtime.OrleansConfigurationException
  langs:
  - csharp
  - vb
  name: OrleansConfigurationException(SerializationInfo, StreamingContext)
  nameWithType: OrleansConfigurationException.OrleansConfigurationException(SerializationInfo, StreamingContext)
  fullName: Orleans.Runtime.OrleansConfigurationException.OrleansConfigurationException(SerializationInfo, StreamingContext)
  type: Constructor
  source:
    remote:
      path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: .ctor
    path: src/Orleans.Core.Abstractions/Exceptions/OrleansConfigurationException.cs
    startLine: 18
  assemblies:
  - Orleans.Core.Abstractions
  namespace: Orleans.Runtime
  example: []
  syntax:
    content: protected OrleansConfigurationException(SerializationInfo info, StreamingContext context)
    parameters:
    - id: info
      type: SerializationInfo
    - id: context
      type: StreamingContext
    content.vb: Protected Sub New(info As SerializationInfo, context As StreamingContext)
  overload: Orleans.Runtime.OrleansConfigurationException.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: Orleans.Runtime
  commentId: N:Orleans.Runtime
  isExternal: false
  name: Orleans.Runtime
  nameWithType: Orleans.Runtime
  fullName: Orleans.Runtime
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Orleans.Runtime.OrleansConfigurationException.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<OrleansConfigurationException>()
  nameWithType: ImmutableExt.AsImmutable<OrleansConfigurationException>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Runtime.OrleansConfigurationException>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of OrleansConfigurationException)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Runtime.OrleansConfigurationException)()
  name.vb: AsImmutable(Of OrleansConfigurationException)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<OrleansConfigurationException>
    nameWithType: ImmutableExt.AsImmutable<OrleansConfigurationException>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Runtime.OrleansConfigurationException>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of OrleansConfigurationException)
    nameWithType: ImmutableExt.AsImmutable(Of OrleansConfigurationException)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Runtime.OrleansConfigurationException)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: Orleans.Runtime.OrleansConfigurationException.#ctor*
  commentId: Overload:Orleans.Runtime.OrleansConfigurationException.#ctor
  isExternal: false
  name: OrleansConfigurationException
  nameWithType: OrleansConfigurationException.OrleansConfigurationException
  fullName: Orleans.Runtime.OrleansConfigurationException.OrleansConfigurationException
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Exception
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: Exception
- uid: SerializationInfo
  isExternal: true
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: SerializationInfo
- uid: StreamingContext
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: StreamingContext
