### YamlMime:ManagedReference
items:
- uid: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator
  commentId: T:Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator
  id: LegacyConsulGatewayListProviderConfigurator
  parent: Orleans.ConsulUtils
  children:
  - Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  langs:
  - csharp
  - vb
  name: LegacyConsulGatewayListProviderConfigurator
  nameWithType: LegacyConsulGatewayListProviderConfigurator
  fullName: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator
  type: Class
  source:
    remote:
      path: src/Orleans.Clustering.Consul/LegacyConsulGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: LegacyConsulGatewayListProviderConfigurator
    path: src/Orleans.Clustering.Consul/LegacyConsulGatewayListProviderConfigurator.cs
    startLine: 10
  assemblies:
  - Orleans.Clustering.Consul
  namespace: Orleans.ConsulUtils
  example: []
  syntax:
    content: 'public class LegacyConsulGatewayListProviderConfigurator : ILegacyGatewayListProviderConfigurator'
    content.vb: >-
      Public Class LegacyConsulGatewayListProviderConfigurator

          Inherits ILegacyGatewayListProviderConfigurator
  inheritance:
  - System.Object
  extensionMethods:
  - Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  commentId: M:Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  id: ConfigureServices(System.Object,IServiceCollection)
  parent: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureServices(Object, IServiceCollection)
  nameWithType: LegacyConsulGatewayListProviderConfigurator.ConfigureServices(Object, IServiceCollection)
  fullName: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices(System.Object, IServiceCollection)
  type: Method
  source:
    remote:
      path: src/Orleans.Clustering.Consul/LegacyConsulGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: ConfigureServices
    path: src/Orleans.Clustering.Consul/LegacyConsulGatewayListProviderConfigurator.cs
    startLine: 13
  assemblies:
  - Orleans.Clustering.Consul
  namespace: Orleans.ConsulUtils
  example: []
  syntax:
    content: public void ConfigureServices(object configuration, IServiceCollection services)
    parameters:
    - id: configuration
      type: System.Object
    - id: services
      type: IServiceCollection
    content.vb: Public Sub ConfigureServices(configuration As Object, services As IServiceCollection)
  overload: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Orleans.ConsulUtils
  commentId: N:Orleans.ConsulUtils
  isExternal: false
  name: Orleans.ConsulUtils
  nameWithType: Orleans.ConsulUtils
  fullName: Orleans.ConsulUtils
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<LegacyConsulGatewayListProviderConfigurator>()
  nameWithType: ImmutableExt.AsImmutable<LegacyConsulGatewayListProviderConfigurator>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of LegacyConsulGatewayListProviderConfigurator)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator)()
  name.vb: AsImmutable(Of LegacyConsulGatewayListProviderConfigurator)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<LegacyConsulGatewayListProviderConfigurator>
    nameWithType: ImmutableExt.AsImmutable<LegacyConsulGatewayListProviderConfigurator>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of LegacyConsulGatewayListProviderConfigurator)
    nameWithType: ImmutableExt.AsImmutable(Of LegacyConsulGatewayListProviderConfigurator)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices*
  commentId: Overload:Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices
  isExternal: false
  name: ConfigureServices
  nameWithType: LegacyConsulGatewayListProviderConfigurator.ConfigureServices
  fullName: Orleans.ConsulUtils.LegacyConsulGatewayListProviderConfigurator.ConfigureServices
- uid: IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: IServiceCollection
