### YamlMime:ManagedReference
items:
- uid: Orleans.Runtime.Configuration
  commentId: N:Orleans.Runtime.Configuration
  id: Orleans.Runtime.Configuration
  children:
  - Orleans.Runtime.Configuration.ApplicationConfiguration
  - Orleans.Runtime.Configuration.BootstrapProviderConfiguration
  - Orleans.Runtime.Configuration.ClientConfiguration
  - Orleans.Runtime.Configuration.ClientConfiguration.GatewayProviderType
  - Orleans.Runtime.Configuration.ClusterConfiguration
  - Orleans.Runtime.Configuration.ConfigurationExtensions
  - Orleans.Runtime.Configuration.GlobalConfiguration
  - Orleans.Runtime.Configuration.GlobalConfiguration.DirectoryCachingStrategyType
  - Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelConfiguration
  - Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelType
  - Orleans.Runtime.Configuration.GlobalConfiguration.LivenessProviderType
  - Orleans.Runtime.Configuration.GlobalConfiguration.ReminderServiceProviderType
  - Orleans.Runtime.Configuration.GrainServiceConfiguration
  - Orleans.Runtime.Configuration.GrainServiceConfigurations
  - Orleans.Runtime.Configuration.GrainTypeConfiguration
  - Orleans.Runtime.Configuration.IGrainServiceConfiguration
  - Orleans.Runtime.Configuration.LogConsistencyConfigurationExtensions
  - Orleans.Runtime.Configuration.NodeConfiguration
  - Orleans.Runtime.Configuration.PerfCountersConfigurationExtensions
  langs:
  - csharp
  - vb
  name: Orleans.Runtime.Configuration
  nameWithType: Orleans.Runtime.Configuration
  fullName: Orleans.Runtime.Configuration
  type: Namespace
  assemblies:
  - Orleans.Core.Legacy
references:
- uid: Orleans.Runtime.Configuration.ApplicationConfiguration
  commentId: T:Orleans.Runtime.Configuration.ApplicationConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: ApplicationConfiguration
  nameWithType: ApplicationConfiguration
  fullName: Orleans.Runtime.Configuration.ApplicationConfiguration
- uid: Orleans.Runtime.Configuration.GrainTypeConfiguration
  commentId: T:Orleans.Runtime.Configuration.GrainTypeConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GrainTypeConfiguration
  nameWithType: GrainTypeConfiguration
  fullName: Orleans.Runtime.Configuration.GrainTypeConfiguration
- uid: Orleans.Runtime.Configuration.ClientConfiguration
  commentId: T:Orleans.Runtime.Configuration.ClientConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: ClientConfiguration
  nameWithType: ClientConfiguration
  fullName: Orleans.Runtime.Configuration.ClientConfiguration
- uid: Orleans.Runtime.Configuration.ClientConfiguration.GatewayProviderType
  commentId: T:Orleans.Runtime.Configuration.ClientConfiguration.GatewayProviderType
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: ClientConfiguration.GatewayProviderType
  nameWithType: ClientConfiguration.GatewayProviderType
  fullName: Orleans.Runtime.Configuration.ClientConfiguration.GatewayProviderType
- uid: Orleans.Runtime.Configuration.ClusterConfiguration
  commentId: T:Orleans.Runtime.Configuration.ClusterConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: ClusterConfiguration
  nameWithType: ClusterConfiguration
  fullName: Orleans.Runtime.Configuration.ClusterConfiguration
- uid: Orleans.Runtime.Configuration.ConfigurationExtensions
  commentId: T:Orleans.Runtime.Configuration.ConfigurationExtensions
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Orleans.Runtime.Configuration.ConfigurationExtensions
- uid: Orleans.Runtime.Configuration.GlobalConfiguration
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GlobalConfiguration
  nameWithType: GlobalConfiguration
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration
- uid: Orleans.Runtime.Configuration.GlobalConfiguration.LivenessProviderType
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration.LivenessProviderType
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GlobalConfiguration.LivenessProviderType
  nameWithType: GlobalConfiguration.LivenessProviderType
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration.LivenessProviderType
- uid: Orleans.Runtime.Configuration.GlobalConfiguration.ReminderServiceProviderType
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration.ReminderServiceProviderType
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GlobalConfiguration.ReminderServiceProviderType
  nameWithType: GlobalConfiguration.ReminderServiceProviderType
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration.ReminderServiceProviderType
- uid: Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelType
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelType
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GlobalConfiguration.GossipChannelType
  nameWithType: GlobalConfiguration.GossipChannelType
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelType
- uid: Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelConfiguration
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelConfiguration
  isExternal: false
  name: GlobalConfiguration.GossipChannelConfiguration
  nameWithType: GlobalConfiguration.GossipChannelConfiguration
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration.GossipChannelConfiguration
- uid: Orleans.Runtime.Configuration.GlobalConfiguration.DirectoryCachingStrategyType
  commentId: T:Orleans.Runtime.Configuration.GlobalConfiguration.DirectoryCachingStrategyType
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GlobalConfiguration.DirectoryCachingStrategyType
  nameWithType: GlobalConfiguration.DirectoryCachingStrategyType
  fullName: Orleans.Runtime.Configuration.GlobalConfiguration.DirectoryCachingStrategyType
- uid: Orleans.Runtime.Configuration.GrainServiceConfigurations
  commentId: T:Orleans.Runtime.Configuration.GrainServiceConfigurations
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: GrainServiceConfigurations
  nameWithType: GrainServiceConfigurations
  fullName: Orleans.Runtime.Configuration.GrainServiceConfigurations
- uid: Orleans.Runtime.Configuration.IGrainServiceConfiguration
  commentId: T:Orleans.Runtime.Configuration.IGrainServiceConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: IGrainServiceConfiguration
  nameWithType: IGrainServiceConfiguration
  fullName: Orleans.Runtime.Configuration.IGrainServiceConfiguration
- uid: Orleans.Runtime.Configuration.GrainServiceConfiguration
  commentId: T:Orleans.Runtime.Configuration.GrainServiceConfiguration
  isExternal: false
  name: GrainServiceConfiguration
  nameWithType: GrainServiceConfiguration
  fullName: Orleans.Runtime.Configuration.GrainServiceConfiguration
- uid: Orleans.Runtime.Configuration.NodeConfiguration
  commentId: T:Orleans.Runtime.Configuration.NodeConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: NodeConfiguration
  nameWithType: NodeConfiguration
  fullName: Orleans.Runtime.Configuration.NodeConfiguration
- uid: Orleans.Runtime.Configuration.BootstrapProviderConfiguration
  commentId: T:Orleans.Runtime.Configuration.BootstrapProviderConfiguration
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: BootstrapProviderConfiguration
  nameWithType: BootstrapProviderConfiguration
  fullName: Orleans.Runtime.Configuration.BootstrapProviderConfiguration
- uid: Orleans.Runtime.Configuration.LogConsistencyConfigurationExtensions
  commentId: T:Orleans.Runtime.Configuration.LogConsistencyConfigurationExtensions
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: LogConsistencyConfigurationExtensions
  nameWithType: LogConsistencyConfigurationExtensions
  fullName: Orleans.Runtime.Configuration.LogConsistencyConfigurationExtensions
- uid: Orleans.Runtime.Configuration.PerfCountersConfigurationExtensions
  commentId: T:Orleans.Runtime.Configuration.PerfCountersConfigurationExtensions
  parent: Orleans.Runtime.Configuration
  isExternal: false
  name: PerfCountersConfigurationExtensions
  nameWithType: PerfCountersConfigurationExtensions
  fullName: Orleans.Runtime.Configuration.PerfCountersConfigurationExtensions
- uid: Orleans.Runtime.Configuration
  commentId: N:Orleans.Runtime.Configuration
  isExternal: false
  name: Orleans.Runtime.Configuration
  nameWithType: Orleans.Runtime.Configuration
  fullName: Orleans.Runtime.Configuration
