### YamlMime:ManagedReference
items:
- uid: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator
  commentId: T:OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator
  id: LegacyZooKeeperMembershipConfigurator
  parent: OrleansZooKeeperUtils
  children:
  - OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure(System.Object,ISiloHostBuilder)
  langs:
  - csharp
  - vb
  name: LegacyZooKeeperMembershipConfigurator
  nameWithType: LegacyZooKeeperMembershipConfigurator
  fullName: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator
  type: Class
  source:
    remote:
      path: src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: LegacyZooKeeperMembershipConfigurator
    path: src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
    startLine: 6
  assemblies:
  - Orleans.Clustering.ZooKeeper
  namespace: OrleansZooKeeperUtils
  example: []
  syntax:
    content: 'public class LegacyZooKeeperMembershipConfigurator : ILegacyMembershipConfigurator'
    content.vb: >-
      Public Class LegacyZooKeeperMembershipConfigurator

          Inherits ILegacyMembershipConfigurator
  inheritance:
  - System.Object
  extensionMethods:
  - OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure(System.Object,ISiloHostBuilder)
  commentId: M:OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure(System.Object,ISiloHostBuilder)
  id: Configure(System.Object,ISiloHostBuilder)
  parent: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator
  langs:
  - csharp
  - vb
  name: Configure(Object, ISiloHostBuilder)
  nameWithType: LegacyZooKeeperMembershipConfigurator.Configure(Object, ISiloHostBuilder)
  fullName: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure(System.Object, ISiloHostBuilder)
  type: Method
  source:
    remote:
      path: src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: Configure
    path: src/Orleans.Clustering.ZooKeeper/LegacyZooKeeperMembershipConfigurator.cs
    startLine: 8
  assemblies:
  - Orleans.Clustering.ZooKeeper
  namespace: OrleansZooKeeperUtils
  syntax:
    content: public void Configure(object configuration, ISiloHostBuilder builder)
    parameters:
    - id: configuration
      type: System.Object
    - id: builder
      type: ISiloHostBuilder
    content.vb: Public Sub Configure(configuration As Object, builder As ISiloHostBuilder)
  overload: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: OrleansZooKeeperUtils
  commentId: N:OrleansZooKeeperUtils
  isExternal: false
  name: OrleansZooKeeperUtils
  nameWithType: OrleansZooKeeperUtils
  fullName: OrleansZooKeeperUtils
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<LegacyZooKeeperMembershipConfigurator>()
  nameWithType: ImmutableExt.AsImmutable<LegacyZooKeeperMembershipConfigurator>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of LegacyZooKeeperMembershipConfigurator)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator)()
  name.vb: AsImmutable(Of LegacyZooKeeperMembershipConfigurator)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<LegacyZooKeeperMembershipConfigurator>
    nameWithType: ImmutableExt.AsImmutable<LegacyZooKeeperMembershipConfigurator>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of LegacyZooKeeperMembershipConfigurator)
    nameWithType: ImmutableExt.AsImmutable(Of LegacyZooKeeperMembershipConfigurator)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure*
  commentId: Overload:OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure
  isExternal: false
  name: Configure
  nameWithType: LegacyZooKeeperMembershipConfigurator.Configure
  fullName: OrleansZooKeeperUtils.LegacyZooKeeperMembershipConfigurator.Configure
- uid: ISiloHostBuilder
  isExternal: true
  name: ISiloHostBuilder
  nameWithType: ISiloHostBuilder
  fullName: ISiloHostBuilder
