### YamlMime:ManagedReference
items:
- uid: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator
  commentId: T:Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator
  id: LegacyAdoNetGatewayListProviderConfigurator
  parent: Orleans.AdoNet.Messaging
  children:
  - Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  langs:
  - csharp
  - vb
  name: LegacyAdoNetGatewayListProviderConfigurator
  nameWithType: LegacyAdoNetGatewayListProviderConfigurator
  fullName: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator
  type: Class
  source:
    remote:
      path: src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: LegacyAdoNetGatewayListProviderConfigurator
    path: src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
    startLine: 9
  assemblies:
  - Orleans.Clustering.AdoNet
  namespace: Orleans.AdoNet.Messaging
  example: []
  syntax:
    content: 'public class LegacyAdoNetGatewayListProviderConfigurator : ILegacyGatewayListProviderConfigurator'
    content.vb: >-
      Public Class LegacyAdoNetGatewayListProviderConfigurator

          Inherits ILegacyGatewayListProviderConfigurator
  inheritance:
  - System.Object
  extensionMethods:
  - Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  commentId: M:Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices(System.Object,IServiceCollection)
  id: ConfigureServices(System.Object,IServiceCollection)
  parent: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator
  langs:
  - csharp
  - vb
  name: ConfigureServices(Object, IServiceCollection)
  nameWithType: LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices(Object, IServiceCollection)
  fullName: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices(System.Object, IServiceCollection)
  type: Method
  source:
    remote:
      path: src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: ConfigureServices
    path: src/AdoNet/Orleans.Clustering.AdoNet/Messaging/LegacyAdoNetGatewayListProviderConfigurator.cs
    startLine: 11
  assemblies:
  - Orleans.Clustering.AdoNet
  namespace: Orleans.AdoNet.Messaging
  syntax:
    content: public void ConfigureServices(object configuration, IServiceCollection services)
    parameters:
    - id: configuration
      type: System.Object
    - id: services
      type: IServiceCollection
    content.vb: Public Sub ConfigureServices(configuration As Object, services As IServiceCollection)
  overload: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Orleans.AdoNet.Messaging
  commentId: N:Orleans.AdoNet.Messaging
  isExternal: false
  name: Orleans.AdoNet.Messaging
  nameWithType: Orleans.AdoNet.Messaging
  fullName: Orleans.AdoNet.Messaging
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<LegacyAdoNetGatewayListProviderConfigurator>()
  nameWithType: ImmutableExt.AsImmutable<LegacyAdoNetGatewayListProviderConfigurator>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of LegacyAdoNetGatewayListProviderConfigurator)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator)()
  name.vb: AsImmutable(Of LegacyAdoNetGatewayListProviderConfigurator)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<LegacyAdoNetGatewayListProviderConfigurator>
    nameWithType: ImmutableExt.AsImmutable<LegacyAdoNetGatewayListProviderConfigurator>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of LegacyAdoNetGatewayListProviderConfigurator)
    nameWithType: ImmutableExt.AsImmutable(Of LegacyAdoNetGatewayListProviderConfigurator)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices*
  commentId: Overload:Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices
  isExternal: false
  name: ConfigureServices
  nameWithType: LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices
  fullName: Orleans.AdoNet.Messaging.LegacyAdoNetGatewayListProviderConfigurator.ConfigureServices
- uid: IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: IServiceCollection
