### YamlMime:ManagedReference
items:
- uid: Orleans.Configuration.AdoNetClusteringClientOptions
  commentId: T:Orleans.Configuration.AdoNetClusteringClientOptions
  id: AdoNetClusteringClientOptions
  parent: Orleans.Configuration
  children:
  - Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
  - Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
  langs:
  - csharp
  - vb
  name: AdoNetClusteringClientOptions
  nameWithType: AdoNetClusteringClientOptions
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions
  type: Class
  source:
    remote:
      path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: AdoNetClusteringClientOptions
    path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
    startLine: 2
  assemblies:
  - Orleans.Clustering.AdoNet
  namespace: Orleans.Configuration
  syntax:
    content: 'public class AdoNetClusteringClientOptions : object'
    content.vb: >-
      Public Class AdoNetClusteringClientOptions

          Inherits Object
  inheritance:
  - System.Object
  extensionMethods:
  - Orleans.Configuration.AdoNetClusteringClientOptions.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
  commentId: P:Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
  id: ConnectionString
  parent: Orleans.Configuration.AdoNetClusteringClientOptions
  langs:
  - csharp
  - vb
  name: ConnectionString
  nameWithType: AdoNetClusteringClientOptions.ConnectionString
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
  type: Property
  source:
    remote:
      path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: ConnectionString
    path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
    startLine: 7
  assemblies:
  - Orleans.Clustering.AdoNet
  namespace: Orleans.Configuration
  summary: "\nConnection string for Sql\n"
  example: []
  syntax:
    content: public string ConnectionString { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConnectionString As String
  overload: Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
  commentId: P:Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
  id: Invariant
  parent: Orleans.Configuration.AdoNetClusteringClientOptions
  langs:
  - csharp
  - vb
  name: Invariant
  nameWithType: AdoNetClusteringClientOptions.Invariant
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
  type: Property
  source:
    remote:
      path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
      branch: api-reference
      repo: https://github.com/mehmetakbulut/orleans.git
    id: Invariant
    path: src/AdoNet/Orleans.Clustering.AdoNet/Options/AdoNetClusteringClientOptions.cs
    startLine: 13
  assemblies:
  - Orleans.Clustering.AdoNet
  namespace: Orleans.Configuration
  summary: "\nThe invariant name of the connector for gatewayProvider&apos;s database.\n"
  example: []
  syntax:
    content: public string Invariant { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Invariant As String
  overload: Orleans.Configuration.AdoNetClusteringClientOptions.Invariant*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Orleans.Configuration
  commentId: N:Orleans.Configuration
  isExternal: false
  name: Orleans.Configuration
  nameWithType: Orleans.Configuration
  fullName: Orleans.Configuration
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Orleans.Configuration.AdoNetClusteringClientOptions.Orleans.Concurrency.ImmutableExt.AsImmutable``1
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  parent: Orleans.Concurrency.ImmutableExt
  definition: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  name: AsImmutable<AdoNetClusteringClientOptions>()
  nameWithType: ImmutableExt.AsImmutable<AdoNetClusteringClientOptions>()
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Configuration.AdoNetClusteringClientOptions>()
  nameWithType.vb: ImmutableExt.AsImmutable(Of AdoNetClusteringClientOptions)()
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Configuration.AdoNetClusteringClientOptions)()
  name.vb: AsImmutable(Of AdoNetClusteringClientOptions)()
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable<AdoNetClusteringClientOptions>
    nameWithType: ImmutableExt.AsImmutable<AdoNetClusteringClientOptions>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<Orleans.Configuration.AdoNetClusteringClientOptions>
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1
    name: AsImmutable(Of AdoNetClusteringClientOptions)
    nameWithType: ImmutableExt.AsImmutable(Of AdoNetClusteringClientOptions)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of Orleans.Configuration.AdoNetClusteringClientOptions)
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  commentId: M:Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
  isExternal: false
  name: AsImmutable<T>(T)
  nameWithType: ImmutableExt.AsImmutable<T>(T)
  fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>(T)
  nameWithType.vb: ImmutableExt.AsImmutable(Of T)(T)
  fullName.vb: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)(T)
  name.vb: AsImmutable(Of T)(T)
  spec.csharp:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable<T>
    nameWithType: ImmutableExt.AsImmutable<T>
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable<T>
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Orleans.Concurrency.ImmutableExt.AsImmutable``1(``0)
    name: AsImmutable(Of T)
    nameWithType: ImmutableExt.AsImmutable(Of T)
    fullName: Orleans.Concurrency.ImmutableExt.AsImmutable(Of T)
  - name: (
    nameWithType: (
    fullName: (
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Orleans.Concurrency.ImmutableExt
  commentId: T:Orleans.Concurrency.ImmutableExt
  parent: Orleans.Concurrency
  isExternal: false
  name: ImmutableExt
  nameWithType: ImmutableExt
  fullName: Orleans.Concurrency.ImmutableExt
- uid: Orleans.Concurrency
  commentId: N:Orleans.Concurrency
  isExternal: false
  name: Orleans.Concurrency
  nameWithType: Orleans.Concurrency
  fullName: Orleans.Concurrency
- uid: Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString*
  commentId: Overload:Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
  isExternal: false
  name: ConnectionString
  nameWithType: AdoNetClusteringClientOptions.ConnectionString
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions.ConnectionString
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Orleans.Configuration.AdoNetClusteringClientOptions.Invariant*
  commentId: Overload:Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
  isExternal: false
  name: Invariant
  nameWithType: AdoNetClusteringClientOptions.Invariant
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions.Invariant
