### YamlMime:ManagedReference
items:
- uid: Orleans.Configuration
  commentId: N:Orleans.Configuration
  id: Orleans.Configuration
  children:
  - Orleans.Configuration.AdoNetClusteringClientOptions
  - Orleans.Configuration.AdoNetClusteringClientOptionsValidator
  - Orleans.Configuration.AdoNetClusteringSiloOptions
  - Orleans.Configuration.AdoNetClusteringSiloOptionsValidator
  - Orleans.Configuration.AdoNetGrainStorageOptions
  - Orleans.Configuration.AdoNetGrainStorageOptionsValidator
  - Orleans.Configuration.AdoNetReminderTableOptions
  - Orleans.Configuration.AdoNetReminderTableOptionsValidator
  - Orleans.Configuration.ApplicationInsightsTelemetryConsumerOptions
  - Orleans.Configuration.AzureTransactionLogOptions
  - Orleans.Configuration.AzureTransactionLogOptionsValidator
  - Orleans.Configuration.ConsulClusteringClientOptions
  - Orleans.Configuration.ConsulClusteringSiloOptions
  - Orleans.Configuration.DynamoDBClusteringOptions
  - Orleans.Configuration.DynamoDBClusteringSiloOptions
  - Orleans.Configuration.DynamoDBGatewayOptions
  - Orleans.Configuration.DynamoDBGrainStorageOptionsValidator
  - Orleans.Configuration.DynamoDBReminderStorageOptions
  - Orleans.Configuration.DynamoDBReminderTableOptions
  - Orleans.Configuration.DynamoDBStorageOptions
  - Orleans.Configuration.LegacyConfigurationExtensions
  - Orleans.Configuration.NewRelicTelemetryConsumerOptions
  - Orleans.Configuration.PubSubOptions
  - Orleans.Configuration.ServiceFabricClusteringOptions
  - Orleans.Configuration.SqsOptions
  - Orleans.Configuration.ZooKeeperClusteringSiloOptions
  - Orleans.Configuration.ZooKeeperGatewayListProviderOptions
  langs:
  - csharp
  - vb
  name: Orleans.Configuration
  nameWithType: Orleans.Configuration
  fullName: Orleans.Configuration
  type: Namespace
  assemblies:
  - Orleans.Core.Legacy
references:
- uid: Orleans.Configuration.LegacyConfigurationExtensions
  commentId: T:Orleans.Configuration.LegacyConfigurationExtensions
  isExternal: false
  name: LegacyConfigurationExtensions
  nameWithType: LegacyConfigurationExtensions
  fullName: Orleans.Configuration.LegacyConfigurationExtensions
- uid: Orleans.Configuration.PubSubOptions
  commentId: T:Orleans.Configuration.PubSubOptions
  parent: Orleans.Configuration
  isExternal: false
  name: PubSubOptions
  nameWithType: PubSubOptions
  fullName: Orleans.Configuration.PubSubOptions
- uid: Orleans.Configuration.ZooKeeperClusteringSiloOptions
  commentId: T:Orleans.Configuration.ZooKeeperClusteringSiloOptions
  isExternal: false
  name: ZooKeeperClusteringSiloOptions
  nameWithType: ZooKeeperClusteringSiloOptions
  fullName: Orleans.Configuration.ZooKeeperClusteringSiloOptions
- uid: Orleans.Configuration.ZooKeeperGatewayListProviderOptions
  commentId: T:Orleans.Configuration.ZooKeeperGatewayListProviderOptions
  isExternal: false
  name: ZooKeeperGatewayListProviderOptions
  nameWithType: ZooKeeperGatewayListProviderOptions
  fullName: Orleans.Configuration.ZooKeeperGatewayListProviderOptions
- uid: Orleans.Configuration.AdoNetClusteringClientOptions
  commentId: T:Orleans.Configuration.AdoNetClusteringClientOptions
  isExternal: false
  name: AdoNetClusteringClientOptions
  nameWithType: AdoNetClusteringClientOptions
  fullName: Orleans.Configuration.AdoNetClusteringClientOptions
- uid: Orleans.Configuration.AdoNetClusteringClientOptionsValidator
  commentId: T:Orleans.Configuration.AdoNetClusteringClientOptionsValidator
  isExternal: false
  name: AdoNetClusteringClientOptionsValidator
  nameWithType: AdoNetClusteringClientOptionsValidator
  fullName: Orleans.Configuration.AdoNetClusteringClientOptionsValidator
- uid: Orleans.Configuration.AdoNetClusteringSiloOptions
  commentId: T:Orleans.Configuration.AdoNetClusteringSiloOptions
  isExternal: false
  name: AdoNetClusteringSiloOptions
  nameWithType: AdoNetClusteringSiloOptions
  fullName: Orleans.Configuration.AdoNetClusteringSiloOptions
- uid: Orleans.Configuration.AdoNetClusteringSiloOptionsValidator
  commentId: T:Orleans.Configuration.AdoNetClusteringSiloOptionsValidator
  isExternal: false
  name: AdoNetClusteringSiloOptionsValidator
  nameWithType: AdoNetClusteringSiloOptionsValidator
  fullName: Orleans.Configuration.AdoNetClusteringSiloOptionsValidator
- uid: Orleans.Configuration.AdoNetGrainStorageOptions
  commentId: T:Orleans.Configuration.AdoNetGrainStorageOptions
  parent: Orleans.Configuration
  isExternal: false
  name: AdoNetGrainStorageOptions
  nameWithType: AdoNetGrainStorageOptions
  fullName: Orleans.Configuration.AdoNetGrainStorageOptions
- uid: Orleans.Configuration.AdoNetGrainStorageOptionsValidator
  commentId: T:Orleans.Configuration.AdoNetGrainStorageOptionsValidator
  isExternal: false
  name: AdoNetGrainStorageOptionsValidator
  nameWithType: AdoNetGrainStorageOptionsValidator
  fullName: Orleans.Configuration.AdoNetGrainStorageOptionsValidator
- uid: Orleans.Configuration.AdoNetReminderTableOptions
  commentId: T:Orleans.Configuration.AdoNetReminderTableOptions
  isExternal: false
  name: AdoNetReminderTableOptions
  nameWithType: AdoNetReminderTableOptions
  fullName: Orleans.Configuration.AdoNetReminderTableOptions
- uid: Orleans.Configuration.AdoNetReminderTableOptionsValidator
  commentId: T:Orleans.Configuration.AdoNetReminderTableOptionsValidator
  isExternal: false
  name: AdoNetReminderTableOptionsValidator
  nameWithType: AdoNetReminderTableOptionsValidator
  fullName: Orleans.Configuration.AdoNetReminderTableOptionsValidator
- uid: Orleans.Configuration.NewRelicTelemetryConsumerOptions
  commentId: T:Orleans.Configuration.NewRelicTelemetryConsumerOptions
  isExternal: false
  name: NewRelicTelemetryConsumerOptions
  nameWithType: NewRelicTelemetryConsumerOptions
  fullName: Orleans.Configuration.NewRelicTelemetryConsumerOptions
- uid: Orleans.Configuration.ServiceFabricClusteringOptions
  commentId: T:Orleans.Configuration.ServiceFabricClusteringOptions
  isExternal: false
  name: ServiceFabricClusteringOptions
  nameWithType: ServiceFabricClusteringOptions
  fullName: Orleans.Configuration.ServiceFabricClusteringOptions
- uid: Orleans.Configuration.SqsOptions
  commentId: T:Orleans.Configuration.SqsOptions
  parent: Orleans.Configuration
  isExternal: false
  name: SqsOptions
  nameWithType: SqsOptions
  fullName: Orleans.Configuration.SqsOptions
- uid: Orleans.Configuration.DynamoDBReminderTableOptions
  commentId: T:Orleans.Configuration.DynamoDBReminderTableOptions
  isExternal: false
  name: DynamoDBReminderTableOptions
  nameWithType: DynamoDBReminderTableOptions
  fullName: Orleans.Configuration.DynamoDBReminderTableOptions
- uid: Orleans.Configuration.DynamoDBReminderStorageOptions
  commentId: T:Orleans.Configuration.DynamoDBReminderStorageOptions
  isExternal: false
  name: DynamoDBReminderStorageOptions
  nameWithType: DynamoDBReminderStorageOptions
  fullName: Orleans.Configuration.DynamoDBReminderStorageOptions
- uid: Orleans.Configuration.DynamoDBClusteringOptions
  commentId: T:Orleans.Configuration.DynamoDBClusteringOptions
  isExternal: false
  name: DynamoDBClusteringOptions
  nameWithType: DynamoDBClusteringOptions
  fullName: Orleans.Configuration.DynamoDBClusteringOptions
- uid: Orleans.Configuration.DynamoDBClusteringSiloOptions
  commentId: T:Orleans.Configuration.DynamoDBClusteringSiloOptions
  isExternal: false
  name: DynamoDBClusteringSiloOptions
  nameWithType: DynamoDBClusteringSiloOptions
  fullName: Orleans.Configuration.DynamoDBClusteringSiloOptions
- uid: Orleans.Configuration.DynamoDBGatewayOptions
  commentId: T:Orleans.Configuration.DynamoDBGatewayOptions
  isExternal: false
  name: DynamoDBGatewayOptions
  nameWithType: DynamoDBGatewayOptions
  fullName: Orleans.Configuration.DynamoDBGatewayOptions
- uid: Orleans.Configuration.AzureTransactionLogOptions
  commentId: T:Orleans.Configuration.AzureTransactionLogOptions
  isExternal: false
  name: AzureTransactionLogOptions
  nameWithType: AzureTransactionLogOptions
  fullName: Orleans.Configuration.AzureTransactionLogOptions
- uid: Orleans.Configuration.AzureTransactionLogOptionsValidator
  commentId: T:Orleans.Configuration.AzureTransactionLogOptionsValidator
  isExternal: false
  name: AzureTransactionLogOptionsValidator
  nameWithType: AzureTransactionLogOptionsValidator
  fullName: Orleans.Configuration.AzureTransactionLogOptionsValidator
- uid: Orleans.Configuration.ApplicationInsightsTelemetryConsumerOptions
  commentId: T:Orleans.Configuration.ApplicationInsightsTelemetryConsumerOptions
  isExternal: false
  name: ApplicationInsightsTelemetryConsumerOptions
  nameWithType: ApplicationInsightsTelemetryConsumerOptions
  fullName: Orleans.Configuration.ApplicationInsightsTelemetryConsumerOptions
- uid: Orleans.Configuration.DynamoDBStorageOptions
  commentId: T:Orleans.Configuration.DynamoDBStorageOptions
  parent: Orleans.Configuration
  isExternal: false
  name: DynamoDBStorageOptions
  nameWithType: DynamoDBStorageOptions
  fullName: Orleans.Configuration.DynamoDBStorageOptions
- uid: Orleans.Configuration.DynamoDBGrainStorageOptionsValidator
  commentId: T:Orleans.Configuration.DynamoDBGrainStorageOptionsValidator
  isExternal: false
  name: DynamoDBGrainStorageOptionsValidator
  nameWithType: DynamoDBGrainStorageOptionsValidator
  fullName: Orleans.Configuration.DynamoDBGrainStorageOptionsValidator
- uid: Orleans.Configuration.ConsulClusteringClientOptions
  commentId: T:Orleans.Configuration.ConsulClusteringClientOptions
  isExternal: false
  name: ConsulClusteringClientOptions
  nameWithType: ConsulClusteringClientOptions
  fullName: Orleans.Configuration.ConsulClusteringClientOptions
- uid: Orleans.Configuration.ConsulClusteringSiloOptions
  commentId: T:Orleans.Configuration.ConsulClusteringSiloOptions
  isExternal: false
  name: ConsulClusteringSiloOptions
  nameWithType: ConsulClusteringSiloOptions
  fullName: Orleans.Configuration.ConsulClusteringSiloOptions
- uid: Orleans.Configuration
  commentId: N:Orleans.Configuration
  isExternal: false
  name: Orleans.Configuration
  nameWithType: Orleans.Configuration
  fullName: Orleans.Configuration
